name-template: '🧰 Rilis inventrie v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## Selamat Datang di Open Project BBTA3 BPPT

  Silahkan mengunjungi website BBTA3 BPPT untuk informasi tentang BBTA3 di http://bbta3.bppt.go.id

  Perlu melakukan chat dengan kami, masuk ke tautan berikut ini http://bit.ly/ChatBBTA3

  Apabila berminat gabung dengan _Open Project_ BBTA3 BPPT silahkan juga menggunakan layanan chat kami.

  ## Perubahan yang Dilakukan
  $CHANGES
categories:
  - title: '💣 Perubahan Total'
    label: 'breaking'
  - title: '🚀 Hal Baru'
    label: 'enhancement'
  - title: '🐛 Koreksi Bug'
    label: 'bug'
  - title: '🔨 Perawatan'
    label: 'maintenance'
  - title: '📝 Dokumentasi'
    label: 'documentation'
  - title: '🔗 Pembaruan Dependency'
    label: 'dependencies'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'documentation'
      - 'dependencies'
      - 'security'
